scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
    - targets:
      - prometheus:9090
      - pushgateway:9091
      - cadvisor:8000

  - job_name: docker
    scrape_interval: 5s
    static_configs:
    - targets:
      - <127.0.0.1>:9323