version: "3"
services:
  api-server:
    container_name: server-complexb
    build:
      dockerfile: Dockerfile
      context: .
    #image: pierrebassily/code:backendlatest
    restart: always
    env_file:
      - ./app/config/dev.env
    ports:
      - "8080:8080"
      - "587:587"
    networks:
      - mern-app
    depends_on:
      - mongo
    volumes:
      - ./upload/images:/server/upload/images:rw
  mongo_new:
    image: mongo:focal
    command: mongod --port 15555
    ports:
      - "15555:15555"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    # command: [--auth]
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8000:8000
    command:
      - '-port=8000'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - mern-app
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - 9091:9091
    networks:
      - mern-app
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheuss:/etc/prometheus
      # - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - mern-app
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  prometheus-data:
    driver: local
    

# loki:
  #   image: grafana/loki:2.2.1
  #   ports:
  #     - "3100:3100"
  #   volumes:
  #     - /root/promtailloki/loki:/etc/loki
  #   command: -config.file=/etc/loki/loki-config.yaml
  #   networks:
  #     - mern-app

  # promtail:
  #   image: grafana/promtail:2.2.1
  #   volumes:
  #     - /var/log:/var/log
  #     - /root/promtailloki/promtail:/etc/promtail 
  #   command: -config.file=/etc/promtail/promtail-config.yaml
  #   networks:
  #     - mern-app
