version: "3"
services:
  api-server:
    container_name: server-complexb
    build:
      dockerfile: Dockerfile
      context: .
    #image: pierrebassily/code:backendlatest
    restart: always
    env_file:
      - ./app/config/dev.env
    ports:
      - "8080:8080"
      - "587:587"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:focal
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8000:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - mern-app
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - 9091:9091
    networks:
      - mern-app
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      # - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  prometheus-data:
    driver: local
    
